### ISSUE TITLE
remove bootstrap.rb

### ISSUE THREAD

**Issue by mburns** [mmi-cookbooks/cookbook-deploy_runner#3]
remove [bootstrap.rb](https://github.com/rackerlabs/cookbook-deploy_runner/blob/master/bootstrap.rb), it doesn't belong here. Move it to cloudmetrics-ops/provision, maybe...

connected to https://github.com/rackerlabs/cloudmetrics-ops/pull/163

**Comment by drenalin23** [comment]
Test.
